use LMS;

SELECT MEMBER_ID, MEMBER_NAME, CITY, MEMBERSHIP_STATUS
FROM LMS_MEMBERS
WHERE MEMBERSHIP_STATUS = 'Permanent';

SELECT DISTINCT M.MEMBER_ID, M.MEMBER_NAME
FROM LMS_MEMBERS M
JOIN LMS_BOOK_ISSUE B ON M.MEMBER_ID = B.MEMBER_ID
WHERE B.BOOK_ISSUE_STATUS = 'Y';

SELECT DISTINCT M.MEMBER_ID, M.MEMBER_NAME
FROM LMS_MEMBERS M
JOIN LMS_BOOK_ISSUE B ON M.MEMBER_ID = B.MEMBER_ID
WHERE B.BOOK_CODE = 'BL000002';

SELECT BOOK_CODE, BOOK_TITLE, AUTHOR
FROM LMS_BOOK_DETAILS
WHERE AUTHOR LIKE 'P%';

SELECT COUNT(*) AS NO_OF_BOOKS
FROM LMS_BOOK_DETAILS
WHERE CATEGORY = 'JAVA';

SELECT CATEGORY, COUNT(*) AS NO_OF_BOOKS
FROM LMS_BOOK_DETAILS
GROUP BY CATEGORY;

SELECT COUNT(*) AS NO_OF_BOOKS
FROM LMS_BOOK_DETAILS
WHERE PUBLICATION = 'Prentice Hall';

SELECT BOOK_CODE, BOOK_TITLE
FROM LMS_BOOK_DETAILS
WHERE BOOK_CODE IN (
    SELECT BOOK_CODE
    FROM LMS_BOOK_ISSUE
    WHERE DATE_ISSUE = CAST('01-APR-2012' AS DATE)
);

SELECT MEMBER_ID, MEMBER_NAME, DATE_REGISTER, DATE_EXPIRE
FROM LMS_MEMBERS
WHERE DATE_EXPIRE < CAST('01-APR-2013' AS DATE);

SELECT MEMBER_ID, MEMBER_NAME, DATE_REGISTER, MEMBERSHIP_STATUS
FROM LMS_MEMBERS
WHERE DATE_REGISTER < CAST('01-MAR-2012' AS DATE)
AND MEMBERSHIP_STATUS = 'Temporary';
